### ISSUE TITLE
Implementation accuracy

### ISSUE THREAD

**Issue by alpapado** [9310gaurav/virtual-adversarial-training#1]
Hello

Can you tell me what accuracy does your implementation achieve? Is is on par with the original paper results?

Thanks,

**Comment by 9310gaurav** [comment]
For SVHN it is on par with the original paper results. For CIFAR 10 some additional preprocessing like ZCA whitening is required to achieve the results.

**Comment by alpapado** [comment]
Cool. Thanks a lot
