### ISSUE TITLE
Regression & SSDKL variant

### ISSUE THREAD

**Issue by akaniklaus** [9310gaurav/virtual-adversarial-training#2]
First of all, thank you for such a great work. In the below repository, they used VAT for regression and also proposed another method called SSDKL, which they claim to outperform VAT in that setting.

https://github.com/ermongroup/ssdkl

Unfortunately, it is not in PyTorch. Hence, I would be glad if you can include a regression example for VAT in this repository; and also include SSDKL technique as well if that is possible. Thank you again!

**Comment by 9310gaurav** [comment]
You are welcome.  Thanks for bringing this work to my attention. I will go through the paper and the code and probably by this weekend will update on what I can do.

**Comment by akaniklaus** [comment]
That would be really cool. Thank you very much!

**Comment by akaniklaus** [comment]
FYI, I have recently tried VAT in regression setting, it was just the matter of using MSE instead of KL divergence. However, it seemed to me that by the equation 6 of the paper, the added noise seems to be optimized with an argmax (and is bounded by epsilon which is hypertuned) whereas in all related repos I have checked it seemed to be static. Can you please let me know if I have a misunderstanding?

https://arxiv.org/pdf/1704.03976.pdf
